# Generated by Django 4.1.7 on 2023-03-23 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familymembermodel',
            old_name='relaion',
            new_name='relation',
        ),
    ]
